version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: glpi_db
    hostname: glpi_db
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi_data
    hostname: glpi_data
    ports:
      - "86:80"
    volumes:
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=America/Toronto
    restart: always
