version: '3.4'
services:
  glpi:
    volumes:
      - glpi_data:/var/www/html/glpi
    restart: unless-stopped
  mariadb:
    volumes:
      - glpi_db:/var/lib/mysql
    restart: unless-stopped

volumes:
  glpi_data:
    external:
      name: glpi_data
  glpi_db:
    external:
      name: glpi_db

networks:
  bridge:
    external:
      name: bridge
